### ISSUE TITLE
Make project installable

### ISSUE THREAD

**Issue by johnidm** [cvqluu/simple_diarizer#1]
Hi @cvqluu, this project is amazing, thanks for sharing.

I have some experience in packaging projects in Python.

What do you think I make these items on your to-do list?

- Add to PyPi (make pip installable)
- requirements.txt

If you authorize me, I will start doing this now and submit pull requests for your review and approval.

**Comment by cvqluu** [comment]
Sure! That sounds good - I haven't had much time to work on adding these things so getting your help would be very much welcome.

I've added you as a collaborator
