### ISSUE TITLE
Latest Python and packages

### ISSUE THREAD

**Issue by andrewmackie** [cvqluu/simple_diarizer#7]
The current release prevents use of Python 3.10 and requires specific versions of Beautiful Soup and PyTube.

I've forked the repo to overcome these version limitations and it's working for me. I haven't made a pull request, however, as your repo doesn't have tests and I don't know whether there is a use case which would be broken by my changes.

Can you please remove these version limitations if they're not needed?

Thanks for the repo - it's effective and much easier to use than SpeechBrain.

**Comment by cvqluu** [comment]
Hi, sorry for the delayed response. Feel free to make the pull request, if the main functionality is working (as covered by the colab notebook) then I am happy to merge those changes. 

It's a good point that I should add some tests however!

**Comment by andrewmackie** [comment]
Thanks and sorry for my delayed response.

I have created a [new Google Colab notebook](https://colab.research.google.com/drive/1num6AViCY3Y_5e8ZzJew8rLz5aMkjqb2?usp=sharing) to test it in Python 3.10.

It works until calling diar.diarize_youtube() - in utls.parse_ttml(), BeautifulSoup attempts to load the lxml parser and fails to do so (in spite of the notebook installing lxml with pip and importing it in the python code). I don't have any more time to chase this down for you, sorry, because it took me a few hours to get Python 3.10 working in Google Colab (those tests would make contributing easier!).

I have created [PR #8](https://github.com/cvqluu/simple_diarizer/pull/8) for you to merge (or not) as you see fit.

**Comment by cvqluu** [comment]
It's okay, the diarize_youtube functionality I plan to depracate support for, so it is not an issue.

I think this repo will be more useful for people with the general functionality working with less strict python requirements anyways. Thanks!
